/* SQL CLASS PROGRESS TRACK */

USE [CURSO]

CREATE TABLE [ALUNO](
    [ID] INT NOT NULL UNIQUE,
    [NOME] NVARCHAR(80) NOT NULL,
    [EMAIL] NVARCHAR(180) NOT NULL,
    [NASCIMENTO] DATETIME NULL,
    [ACTIVE] BIT NOT NULL DEFAULT(0), /*PARA DEFINIR O VALOR PADRAO E PODER MUDAR 
    DE NULL PARA NOT NULL CASO NECESSARIO*/
    CONSTRAINT [PK_ALUNO] PRIMARY KEY ([ID]),
    CONSTRAINT [UQ_ALUNO_EMAIL] UNIQUE ([EMAIL])

)
GO

ALTER TABLE [ALUNO]
    ADD [DOCUMENT] NVARCHAR(11)

ALTER TABLE [ALUNO]
    DROP COLUMN [DOCUMENT]

ALTER TABLE [ALUNO]
    ALTER COLUMN [DOCUMENT] CHAR(11) 

ALTER TABLE [ALUNO]
    DROP CONSTRAINT [PK_ALUNO]
