SELECT TOP 100 --DISTINCT PARA TRAZER APENAS CAMPOS DIFERENTES
    MIN [CATEGORIA_ID],
    [ID], [NOME]
FROM
    [CATEGORIA]

SELECT TOP 100
    [ID] AS [CODIGO], -- APELIDO PARA A COLUNA 
    [NOME], 
    [CATEGORIA_ID] 
FROM
    [CURSO]
WHERE
    [ID] = 1 AND --OR / IN (1,3) PEGA TODOS OS VALORES ESPECIFICADOS / BETWEEN (VALOR 1) AND (VALOR 2)
    [NOME] IS NOT NULL LIKE '%FUNDAMENTOS%' --% NO INICIO TERMINA COM A PALAVRA ESPECIFICADA / % NO FINAL COMÇA COM A PALAVRA ESPECIFICADA / % NO INICIO E NO FINAL QUER DIZER QUE CONTEM A PALAVRA ESPECIFICADA
    [CATEGORIA_ID] = 1
ORDER BY
    [NOME], [ID], [CATEGORIA_ID] --ASCENDENT OR DESCENDENT

-- MIN PARA PEGAR O MENOR VALOR DA COLUNA
-- MAX PARA PEGAR O MAIOR VALOR
-- COUNT PARA CONTAR QUATNAS ENTRADAS NA COLUNA
-- AVG PARA PEGAR A MEDIA DE VALORES DA COLUNA
-- SUM PARA SOMAR TODOS OS VALORES DA COLUNA

SELECT TOP 100
    [CURSO].[ID],
    [CURSO].[NOME],
    [CATEGORIA].[ID] AS [CATEGORIA],
    [CATEGORIA].NOME
FROM
    [CURSO]
    INNER JOIN [CATEGORIA]
        ON [CURSO].[CATEGORIA_ID] = [CATEGORIA].[ID]
-- LEFT JOIN PEGA TODOS OS ITENS RELACIONADOS AO PRIMEIRO RELATIVO (CURSO)
-- RIGHT JOIN PEGA TODOS OS ITENS RELACIONADOS AO SEGUNDO RELATIVO (CATEGORIA)
-- FULL OUTER JOIN PEGA TODOS OS ITENS DOS 2 RELATIVOS

SELECT TOP 100
    [ID], [NOME]
FROM
    [CURSO]

UNION -- VAI MESCLAR AS DUAS TABELAS EM UMA SÓ DESDE QUE TENHA SIDO LISTADO OS MESMOS ITENS
UNION ALL -- TRAZ TODAS AS INFORMAÇÕES MAS EVITA DADOS DUPLICADOS

SELECT TOP 100
    [ID], [NOME]
FROM
    [CATEGORIA]


CREATE OR ALTER VIEW vsContagemCrusosPorCategoria
SELECT TOP 100
    [CATEGORIA].[NOME], -- TODOS OS ITENS AQUI DEVEM ESTAR NO GROUP BY
    COUNT ([CURSO].[CATEGORIA_ID]) AS [CURSO]
FROM
    [CATEGORIA]
    INNER JOIN [CURSO] ON [CURSO].[CATEGORIA] = [CATEGORIA].[ID]
GROUP BY
    [CATEGORIA].[NOME],
    [CURSO].[CATEGORIA_ID]
HAVING
    COUTN ([CURSO].[CATEGORIA_ID]) > 1

--PARA O VIEW CRIAR NOVA QUERY COM SELECT * FROM vsContagemCrusosPorCategoria
-- BASICAMENTE CRIA UMA FUNÇAO DA QUERY PARA CHAMAR EM OUTRO LUGAR
-- NAO PODE TER WHERE DENTRO DAS VIEWS MAS PODE TER DEPOIS DE CHAMAR EM OUTRA QUERY