USE [CURSO]

CREATE TABLE [ALUNO](
    [ID] INT NOT NULL UNIQUE,
    [NOME] NVARCHAR(80) NOT NULL,
    [EMAIL] NVARCHAR(180) NOT NULL,
    [NASCIMENTO] DATETIME NULL,
    [ACTIVE] BIT NOT NULL DEFAULT(0), /*PARA DEFINIR O VALOR PADRAO E PODER MUDAR 
    DE NULL PARA NOT NULL CASO NECESSARIO*/
    CONSTRAINT [PK_ALUNO] PRIMARY KEY ([ID]),
    CONSTRAINT [UQ_ALUNO_EMAIL] UNIQUE ([EMAIL])

)
GO

CREATE INDEX[IX_ALUNO_EMAIL] ON [ALUNO]([EMAIL])

ALTER TABLE [ALUNO]
    ADD [DOCUMENT] NVARCHAR(11)

ALTER TABLE [ALUNO]
    DROP COLUMN [DOCUMENT]

ALTER TABLE [ALUNO]
    ALTER COLUMN [DOCUMENT] CHAR(11) 

ALTER TABLE [ALUNO]
    DROP CONSTRAINT [PK_ALUNO]

CREATE TABLE [CURSO](
    [ID] INT NOT NULL IDENTITY(1,1),
    [NOME] NVARCHAR(80) NOT NULL,
    [CATEGORIA_ID] INT NOT NULL,
    
    CONSTRAINT [PK_ALUNO] PRIMARY KEY ([ID]),
    CONSTRAINT [FK_CATEGORIA_CURSO] FOREIGN KEY([CATEGORIA_ID])
        REFERENCES[CATEGORIA]([ID])
)
GO

CREATE TABLE [CATEGORIA](
    [ID] INT NOT NULL UNIQUE,
    [NOME] NVARCHAR(80) NOT NULL,
    
    CONSTRAINT [PK_CATEGORIA] PRIMARY KEY ([ID])
)
GO

CREATE TABLE [PROGRESSO_CURSO](
    [ALUNO_ID] INT NOT NULL UNIQUE,
    [CURSO_ID] INT NOT NULL UNIQUE,
    [PROGRESSO] INT NOT NULL UNIQUE,
    [ULTIMA_ATUALIZACAO] DATETIME NOT NULL DEFAULT(GETDATE()),

    CONSTRAINT PK_PROGRESSO_CURSO PRIMARY KEY ([ALUNO_ID], [CURSO_ID])
)
GO