INSERT INTO [CATEGORIA]([NOME]) VALUES ('BACKEND')
INSERT INTO [CATEGORIA]([NOME]) VALUES ('FRONTEND')
INSERT INTO [CATEGORIA]([NOME]) VALUES ('MOBILE')

INSERT INTO [CURSO]([NOME],[CATEGORIA]) VALUES('FUNDAMENTOS DE C#', 1)
INSERT INTO [CURSO]([NOME],[CATEGORIA]) VALUES('FUNDAMENTOS DE OOP', 1)
INSERT INTO [CURSO]([NOME],[CATEGORIA]) VALUES('ANGULAR', 2)
INSERT INTO [CURSO]([NOME],[CATEGORIA]) VALUES('FLUTTER', 3)

