--PROCEDURE SAO FUNÇOES CRIADAS SIMILARES AO VIEW PARA SEREM EXECUTADAS EM OUTRAS QUERIES
-- POR SER FUNÇÕES PODEM SER DECLARADAS VARIAVEIS DENTRO DAS PROCEDURES
-- SINTAXE
CREATE OR ALTER PROCEDURE [NOME DA PROCEDURE] AS
    DECLARE @ID INT
    SET @ID = 9
    SELECT * FROM [CURSO] WEHRE [ID] = @ID

DROP PROCEDURE [NOME DA PROCEDURE]

CREATE OR ALTER PROCEDURE [spListCourse]
    @Category NVARCHAR(60),
    @PAR2 NVARCHAR(60)
AS
    decalre @CategoryId INT
    SET @CategoryId = (SELECT TOP 1 [ID] FROM [CATEGORIA] WHERE [NOME] = @Category)

    SELECT * FROM [CURSO] WHERE [CATEGORIA_ID] = @CategoryId

-- em outra query 
EXEC [spListCourse] 'Backend', 'PARAMETRO 2' -- valor para ser colocado na variavel da procedure
