BEGIN TRANSACTION
    UPDATE
        [CATEGORIA]
    SET
        [NOME] = 'BACKEND'
    WHERE
        [ID] = 1
ROLLBACK --VERIFICAR SE ESTA OK, CASO OK, SUBSTITUIR PELO COMMIT

BEGIN TRANSACTION
    DELETE FROM
        [CURSO]
    WHERE
        [CATEGORIA_ID] = 3 --PREFERENCIALMENTE DELETAR PELO ID PARA EVITAR DE APAGAR MUITOS DADOS E FAZER BACK DA BASE ANTES DE COMEÇAR

    DELETE FROM
        [CATEGORIA]
    WHERE
        [ID] = 3
ROLLBACK
